KitwareMedical/SlicerVirtualReality

- SuperBuild/External_VTKRenderingOpenVR.cmake
Slicer now builds with VTK source in <Slicer-Build-Dir>/VTKv9
> CMAKE: Update VTK_SOURCE_DIRECTORY to VTKv9

- CMakeLists.txt
Instead of openvr_api.dll, mistakenly openvr_api.lib was included in the package.
The change was only tested on Windows, but other platforms might need a similar fix, too.
> BUG: Fixed packaging error on Windows

- VirtualReality/Logic/vtkSlicerVirtualRealityLogic.cxx
- VirtualReality/Logic/vtkSlicerVirtualRealityLogic.h
- VirtualReality/MRML/vtkMRMLVirtualRealityViewNode.cxx
- VirtualReality/MRML/vtkMRMLVirtualRealityViewNode.h
- VirtualReality/Resources/UI/qSlicerVirtualRealityModuleWidget.ui
- VirtualReality/Widgets/CMakeLists.txt
- VirtualReality/Widgets/qMRMLVirtualRealityView.cxx
- VirtualReality/Widgets/qMRMLVirtualRealityView.h
- VirtualReality/Widgets/qMRMLVirtualRealityView_p.h
- VirtualReality/qSlicerVirtualRealityModule.cxx
- VirtualReality/qSlicerVirtualRealityModule.h
- VirtualReality/qSlicerVirtualRealityModuleWidget.cxx
- VirtualReality/qSlicerVirtualRealityModuleWidget.h
- Separated setReferenceViewNode(vtkMRMLNode*) and updateViewpointFromReferenceView() methods from each other and made them available on the GUI.
- Added updating of view from reference view to the toolbar.
- Use Cameras module to get camera from view node (instead of going through the layout manager), this allowed setDefaultReferenceView() to be implemented in module logic.
- Improved updateViewFromReferenceViewCamera implementation: the method in RenderWindow->InitializeViewFromCamera(cam) has two major issues: it puts the headset in the focal point (so we need to step back to see the full content) and it snaps view direction to the closest axis (so it does not reproduce the reference view orientation accurately).
> Improved setting virtual reality view from reference view camera

- CMakeLists.txt
- VirtualReality/Logic/vtkSlicerVirtualRealityLogic.cxx
- VirtualReality/MRML/vtkMRMLVirtualRealityViewNode.cxx
- VirtualReality/MRML/vtkMRMLVirtualRealityViewNode.h
- VirtualReality/Widgets/qMRMLVirtualRealityView.cxx
- VirtualReality/Widgets/qMRMLVirtualRealityView_p.h
Controller transforms are created (or re-referenced if already existing) when a valid VR view node is set.
At present nodes are never destroyed.
> Adding population of controller transforms

- SuperBuild/External_VTKRenderingOpenVR.cmake
Follow r27473 (COMP: Update VTK to include version change from 9.0 to
8.2. Fixes #4623) and r27486 (ENH: Rename VTK external project removing
version number), the associated external project and source tree are
named "VTK".
> COMP: Fix extension build using correct VTK source directory

- VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractor.h
- VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.h
Some users find it counterintuitive that the grip button does the basic functions while the trigger button does nothing. That change was made so that the trigger button is left for the laser and UI manipulation. Since those developments are delayed significantly, it makes sense to add back the "grip objects and world" function back to the trigger button as well.
It is done in a configurable way. The interactor style has a new SetTriggerButtonFunction method that takes a string. If the string is empty then the trigger button will not do anything. If it is the constant accessible with GetButtonFunctionStringGripObjectsAndWorld, then it will be the same as what the grip button currently does as well. The latter is the default for now.
> ENH: Make trigger button configurable

- CMakeLists.txt
- SuperBuildPrerequisites.cmake
This commit is a follow-up of 70d5a3b49 (Fix extension build on macOS by
replacing real Virtual Reality module by a placeholder).
Since the extension build-system expects an inner-build directory
on all platform, this commit keeps the SuperBuild structure by:
- updating "SuperBuildPrerequisites" to list no external project dependencies.
- include "VirtualRealityStub" module source in the inner build
> COMP: Fix macOS packaging ensuring extension has a superbuild layout

- SuperBuild/External_vtkRenderingOpenVR.cmake
- SuperBuild/External_vtkRenderingVR.cmake
* vtkRenderingVR: Remove irrelevant VR_INCLUDE_DIR, VR_LIBRARY and
VTK_VR_OBJECT_FACTORY introduced in 8c65442e2 (COMP: Update
build-system to support against VTK >= 9.1)
* Consistently use _module_subdir, _module_name and EP_SOURCE_DIR
CMake variables.
> STYLE: Improve external project consistency

- VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.cxx
vtkInteractorStyle::OnMove3D is called for controllers AND the head mounted display.
OnMove3D then calls DelegateInteractionEventToDisplayableManagers which has an if statement that throws errors if device is not a controller. Thus you would constantly get this error.
> BUG: Fixes issue on Oculus that throws error constantly when used

- VirtualReality/Widgets/qMRMLVirtualRealityView.cxx
This commit fixes a regression introduced in previous commit 87fc5f9 (BUG: Fix retrieval of OpenVR last post updating VTK) using the expected function name.
> COMP: Fix build using renamed API to retrieve OpenVR pose

- VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractor.h
Following 1c36e4031 (ENH: Update integration to support VTK 9.1), VTK was updated to a version where RecognizeComplexGesture was not virtual anymore in the base class (due to the integration of kitware/VTK@af0fab486 (Clean up VR and OpenVR classes)).
This commit re-introduces the support for custom complex gesture handling based of VTK MR-9892.
See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9892
SlicerVirtualReality implementation details:
* The implementation of both `HandleGripEvents()` and `RecognizeComplexGesture()` was updated by removing the handling specific to Rotate and Pan to only keep he pinch event.
* The update of the Scale was removed.
* Call to `StartingPhysicalEventPoses()` originally introduced though both SlicerVirtualReality@b6815f1cb and kitware/VTK@803d3a327 …
> BUG: Restore complex gesture support

- VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.h
This commit initiates renaming of the interactor style event callback functions to support the action based input model introduced in https://github.com/Slicer/VTK/commit/b7f02e6225bff280c16f2abf44aca216fcaf973d
This commit adds support for `Select3DEvent` and `ViewerMovement3DEvent`.
- Select3DEvent: The action performed when this event is fired is defined by calling MapInputToAction (see [1]).
- ViewerMovement3DEvent: Gives users the ability to fly by calling Dolly3D(). VTK's interactor style offers additional behavior to move around.
[1] https://gitlab.kitware.com/vtk/vtk/-/blob/master/Rendering/VR/vtkVRInteractorStyle.cxx#L61
Future commits could focus on:
- Completing synchronization of this class with `vtkVRInteractorStyle`:
- Add support for Grounded movement style for …
> Fix interaction support renaming VR interactor style callback functions

- VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractor.h
This commit renames the function from `HandleGripEvents` to `HandleComplexGestureEvents` to account for the change introduced through VTK MR-9892.
See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9892
It fixes error like the following:
```
In file included from /path/to/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx:21: /path/to/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.h:49:16: error: ‘virtual void vtkVirtualRealityViewInteractor::HandleGripEvents(vtkEventData*)’ marked ‘override’, but does not override
49 |   virtual void HandleGripEvents(vtkEventData* ed) override;
|                ^~~~~~~~~~~~~~~~
```
> COMP: Fix build accounting for vtkVirtualRealityViewInteractor API change

- VirtualReality/qSlicerVirtualRealityModule.cxx
Remove the "externals" sub-directory that was specific to branch Slicer/VTK@slicer-v9.1.20220125-efbe2afc2 integrating commit Slicer/VTK@0ba7af630 (`[Backport MR-8123] vtk_module_build: Ensure external modules build directory are not overwritten`)
Since the approach originally proposed in VTK MR-8123 was superseded by MR-9097 there is no need to specify the "externals" sub-directory.
> BUG: Fix lookup of manifest file from build tree

- VirtualReality/MRML/CMakeLists.txt
- VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractorObserver.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractorObserver.h
- VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.h
- VirtualReality/Widgets/qMRMLVirtualRealityView.cxx
- VirtualReality/Widgets/qMRMLVirtualRealityView.h
- VirtualReality/Widgets/qMRMLVirtualRealityView_p.h
Addressing issues highlighted in Slicer/Slicer@1cc3b2c62, this commit introduces the `vtkVirtualRealityViewInteractorObserver` class. This addition streamlines event delegation to MRML displayable managers and their associated widgets by leveraging observation of the interactor style.
The modification enables the `vtkVirtualRealityViewInteractorStyle` to inherit from `vtkOpenVRInteractorStyle`, eliminating the need for redundant code implementation and duplication.
It also updates the use of `MapInputToAction()` to map "eventId to state" following the VTK refactoring introduced in kitware/VTK@b7f02e622 (`update openvr to action based input model`).
------------
This is also required the following VTK commit[^1]:
```
[SlicerVirtualReality] ENH: Update OpenVR json binding to map right and …
```
> BUG: Fix integration with updated Slicer event delegation and VTK OpenVR API

- VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx
This follows up on Kitware/VTK@c07e01864 (ENH: Generalize handling of complex gesture events in VR) where the input check based of "vtkEventDataDeviceInput::Grip" was removed from HandleComplexGestureEvents.
> BUG: Ensure handling of gesture triggers the "End" event

- VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractor.h
- VirtualReality/MRML/vtkVirtualRealityViewInteractorObserver.cxx
Since complex gesture are not associated with a specific controller, the associated event will be a synthesized one not associated with any particular device.
> BUG: Do not report "Unrecognized device" if handling complex gesture

- VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractorObserver.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractorObserver.h
- VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.cxx
- VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.h
The functions `OnStartGesture()` and `OnEndGesture()` have been renamed to `StartGesture()` and `EndGesture()`. This aligns their signatures with the corresponding virtual functions in the `vtkInteractorStyle` class. Subsequently, these functions are now called from the VR interactor style functions `HandleComplexGestureEvents()` and `RecognizeComplexGesture()`.
> ENH: Invoke "(Start/End)Gesture" from the gesture recognition handler

- VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.cxx
This commit fixes the incorrect and unnecessary conversion from axis-angle to quaternion inadvertently introduced in 503ef1d ("ENH: Add VR interactor style class for transforming objects in MRML", 2018-08-31).
The additional conversion, introduced in the mentioned commit, was redundant since the event orientations (internally set using `vtkVRRenderWindowInteractor::ConvertPoseToWorldCoordinates`, itself introduced in kitware/VTK@803d3a327d, "ENH: Use pose matrices instead of camera parameters for VR controllers", 2018-09-25) are already in quaternion format.
The redundant conversion was leading to an invalid transformation of the selected object.
Reported by @LucasGandel and @sankhesh
> BUG: Fix Computation of Interaction Transform Used in PositionProp

- VirtualReality/MRML/vtkVirtualRealityViewInteractorObserver.cxx
The `Elevation3DEvent` is checked explicitly due to an issue fixed in MR-10771. See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10771
Since it was integrated in Slicer `5.7.0-2023-12-21` (revision 32659) through https://github.com/Slicer/Slicer/pull/7503, we include the explicit test with `Elevation3DEvent` for Slicer version `< 5.8`
> BUG: Workaround vtkCommand::EventHasData missing event adding explicit check

- VirtualReality/MRML/vtkVirtualRealityViewInteractorStyle.cxx
Related to:
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/80
> ENH: Update interactor style to use runtime-agnostic API to retrieve poses

- VirtualReality/MRML/vtkMRMLVirtualRealityViewNode.cxx
- VirtualReality/MRML/vtkMRMLVirtualRealityViewNode.h
- VirtualReality/Widgets/qMRMLVirtualRealityView.cxx
* Explain why skipping registration of View and Camera displayable managers
* Improve VirtualRealityViewNode doxygen grouping members 
* Fix comments in `vtkMRMLVirtualRealityViewNode` "CreateDefault" functions
> DOC: Update comments and docstrings in `vtkMRMLVirtualRealityViewNode` and `qMRMLVirtualRealityView`

- VirtualReality/MRML/vtkMRMLVirtualRealityViewNode.cxx
- VirtualReality/MRML/vtkMRMLVirtualRealityViewNode.h
- VirtualReality/Widgets/qMRMLVirtualRealityView.cxx
- VirtualReality/Widgets/qMRMLVirtualRealityView_p.h
The following changes are done anticipating subsequent commits introducing support for both `OpenVR` and `OpenXR` 
-----------
Generalize updates of node attributes to all type of devices and introduce two distinct functions:
* `updateTransformNodeFromDevice`
* `updateTransformNodeAttributesFromDevice`
All transform nodes are now consistently set with these attributes:
* `VirtualReality.<DeviceType>Active`
* `VirtualReality.<DeviceType>Connected`
* `VirtualReality.PoseValid`
* `VirtualReality.PoseStatus`
where `<DeviceType>` may be "HMD", "Controller" or "Tracker"
----------
Simplify introducing `CreateDefaultTrackerTransformNode` API. Similarly to HMD, left and right controllers, this commit updates the `vtkMRMLVirtualRealityViewNode` API to support creating default transform nodes …
> Decouple update of transform node matrix and attribute

- CMakeLists.txt
Follow-up of 240a60a (ENH: Add support for "OpenXR" XR runtime) integrated through https://github.com/KitwareMedical/SlicerVirtualReality/pull/149
> COMP: Fix openxr_loader library windows install rule

- SuperBuild/External_OpenXR-SDK.cmake
Follow-up of 240a60a (ENH: Add support for "OpenXR" XR runtime) integrated through https://github.com/KitwareMedical/SlicerVirtualReality/pull/149
Previously, `lib` was assumed for CMAKE_INSTALL_LIBDIR, which caused issues on some builds where `GNUInstallDirs` defaulted `CMAKE_INSTALL_LIBDIR` to `lib64`.
> COMP: Fix linux build explicitly setting lib install dir

- FetchVTKExternalModule.cmake
This change is done anticipating the integration of https://github.com/KitwareMedical/SlicerVirtualReality/pull/151 adding `vtkRenderingOpenXRRemoting` requiring  https://github.com/KitwareMedical/VTKExternalModule/commit/bf0bd2b952376485213227c542ea28f87a20300e (`Update vtkmodule-config to ensure find_dependency macro is always available`) originally integrated through https://github.com/KitwareMedical/VTKExternalModule/pull/3
List of changes:
```
$ git shortlog 50f1c5be9..37ade3c26 --no-merges
Chris Harris (1):
Add VTK_WHEEL_BUILD option
Jean-Christophe Fillion-Robin (6):
Add support for externally building tests of a VTK modules
Update vtkmodule-config to ensure find_dependency macro is always available
Add SuperBuild support
Remove redundant BUILD_TESTING option
COMP: Support …
```
> COMP: Update VTKExternalModule to ensure find_dependency macro is always available

- VirtualReality/Logic/vtkSlicerVirtualRealityLogic.cxx
- VirtualReality/Logic/vtkSlicerVirtualRealityLogic.h
- VirtualReality/MRML/vtkMRMLVirtualRealityViewNode.h
- VirtualReality/Widgets/qMRMLVirtualRealityView.cxx
- VirtualReality/qSlicerVirtualRealityModule.cxx
- VirtualReality/qSlicerVirtualRealityModule.h
- VirtualReality/qSlicerVirtualRealityModuleWidget.cxx
Adds enhancements to the "XR Runtime" combobox, including disabling the combobox if hardware is connected, saving and restoring the last XR runtime from settings and populating the combobox based on supported XR runtimes.
Additionally, the code has been refactored to introduce the `updateDefaultViewNodeFromSettings()` function and simplify the logic by explicitly initializing the `ActiveViewNode`.
> XR Runtime Combobox Enhancements

- CMakeLists.txt
- SuperBuild/External_OpenXRRemoting.cmake
- SuperBuild/External_vtkRenderingOpenXRRemoting.cmake
- SuperBuildPrerequisites.cmake
- VirtualReality/CMakeLists.txt
- VirtualReality/MRML/CMakeLists.txt
- VirtualReality/MRML/vtkMRMLVirtualRealityConfigure.h.in
- VirtualReality/MRML/vtkMRMLVirtualRealityViewNode.cxx
- VirtualReality/MRML/vtkMRMLVirtualRealityViewNode.h
- VirtualReality/Resources/UI/qSlicerVirtualRealityModuleWidget.ui
- VirtualReality/Widgets/qMRMLVirtualRealityView.cxx
- VirtualReality/Widgets/qMRMLVirtualRealityView_p.h
- VirtualReality/qSlicerVirtualRealityModule.cxx
- VirtualReality/qSlicerVirtualRealityModuleWidget.cxx
- VirtualReality/qSlicerVirtualRealityModuleWidget.h
This commit adds support for OpenXR Remoting by adding the `OpenXRRemoting` and `vtkRenderingOpenXRRemoting` external projects. It also updates the view node by adding "Remoting" and "PlayerIPAddress" properties. The corresponding UI updates include a checkbox for toggling remoting and a `QLineEdit` for entering the IP address.
The macro `SlicerVirtualReality_HAS_OPENXRREMOTING_SUPPORT` is added to `vtkMRMLVirtualRealityConfigure.h.in` to conditionally include code specific to OpenXR remoting.
The "Remoting" checkbox and "PlayerIPAddress" line edit are disabled if an active connection has been established.
To fix the issue of `wglDXRegisterObjectNV failed in RegisterSharedTexture()` in OpenXRRemoting, the OpenXRRemoting HelperWindow MultiSamples property is explicitly set to 0.
To ensure …
> Add OpenXRRemoting support

- CMakeLists.txt
Since attempting to build on macOS results into few errors described below, this commit sets the default value for `SlicerVirtualReality_HAS_OPENXR_SUPPORT` to `OFF`.
For future reference, see https://github.com/KitwareMedical/SlicerVirtualReality/pull/150#issue-2060665294
> COMP: Disable OpenXR runtime build by default on macOS

- CMakeLists.txt
Add comments and exclude install rules on macOS where the fix-up process usually takes care of packaging dependencies.
Once integrated, the commits prefixed with `STYLE:` will be added to the `.git-blame-ignore-revs`[^1] file.
[^1]: https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/
> Exclude OpenVR and OpenXR library install rules on macOS

- FetchVTKExternalModule.cmake
- SuperBuild/External_vtkRenderingOpenVR.cmake
- SuperBuild/External_vtkRenderingOpenXR.cmake
- SuperBuild/External_vtkRenderingOpenXRRemoting.cmake
- SuperBuild/External_vtkRenderingVR.cmake
This updates VTKExternalModule and set the Python module install destination install the VTK modules similarly to the location in Slicer core, it is also done anticipating the support for packaging VTK modules on macOS.
List of VTKExternalModule changes:
```
$ git shortlog 37ade3c26..3a290ec10 --no-merges
Jean-Christophe Fillion-Robin (1):
Support customizing Python module install destination
```
Related:
* https://github.com/KitwareMedical/VTKExternalModule/pull/8
> COMP: Update VTK external projects to set python module destination

- SuperBuild/External_OpenXR-SDK.cmake
This release primarily adds new ratified functionality describing the loader interaction with runtimes and API layers. Corresponding definitions are now in the official openxr_loader_negotiation.h generated header, rather than the loader_interfaces.h header previously shipped only with the OpenXR-SDK-Source repository. This change only affects vendors of runtimes and API layers as well as contributors to the OpenXR loader: applications do not directly use this API, the loader uses it on their behalf. A number of other small fixes are also included.
-   Registry
-   Extension reservation: Update author ID and reserve extensions
for Varjo. (internal MR 3083)
-   Extension reservation: Reserve 10 extension ids each for
ANDROIDX & ANDROIDSYS. (internal MR 3086)
-   Khronos ratified addition: …
> ENH: Update OpenXR SDK from 1.0.26 to 1.0.33

- SuperBuild/External_vtkRenderingOpenVR.cmake
- SuperBuild/External_vtkRenderingOpenXR.cmake
- SuperBuild/External_vtkRenderingOpenXRRemoting.cmake
- SuperBuild/External_vtkRenderingVR.cmake
Clearing `CMAKE_INSTALL_NAME_TOOL` is crucial to ensure that the installed VTK libraries have their ID associated with a full path. This step is required for the fix-up process to work as expected.
Follow-up of these pull requests:
* https://github.com/Slicer/Slicer/pull/7537
* https://github.com/Slicer/Slicer/pull/7540
> COMP: Clear CMAKE_INSTALL_NAME_TOOL to fix packaging of VTK modules on macOS

- VirtualReality/Widgets/qMRMLVirtualRealityView.cxx
Conditionally register the transform displayable manager to account for changes introduced in Slicer/Slicer@158d74bdf9 (`ENH: Clean up vtkMRMLLinearTransformsDisplayableManager implementation`, 2024-02-16)
Related pull requests:
* https://github.com/Slicer/Slicer/pull/7590
> BUG: Support updated Slicer displayable manager implementation

- DeveloperGuide.md
- README.md
In the README:
- Revise the top-level and Setup sections to reflect OpenXR support.
- Update existing headset setup instructions to cover both OpenXR and OpenVR setups, with OpenXR being enabled by default. Added a note at the end of the section explaining how to enable OpenVR support.
- Add new sections for "Hololens 2" and "Meta Quest" headsets
- Add entries for "Supported headsets" and "Supported XR modality" to each headset section
- Add "How to use hand interaction" section
- Update the Contributors section to acknowledge @LucasGandel and @sankhesh.
In the DeveloperGuide:
- Remove obsolete build instructions.
- Update Python snippet.
- Add references to the documentation of associated VTK modules.
- Add the "Mapping of Controller Action to VTK event" section.
> DOC: Update README and DeveloperGuide to document OpenXR backend support

- VirtualReality/MRMLDM/vtkMRMLVirtualRealityViewDisplayableManagerFactory.cxx
- VirtualReality/MRMLDM/vtkMRMLVirtualRealityViewDisplayableManagerFactory.h
- VirtualReality/Widgets/qMRMLVirtualRealityView.cxx
This commit added a new, simplified vtkSingleton to vtkAddon: https://github.com/Slicer/vtkAddon/commit/3f317421da77b9f6fd48aaf40608545db4fec3e0 This required a simplification of the vtkMRMLVirtualRealityViewDisplayableManagerFactory singleton class.
> COMP: Fix build error in Slicer-5.7 after vtkSingleton update in vtkAddon
